### ISSUE TITLE
A few things.

### ISSUE THREAD

**Issue by b-t-k** [jmcphers/p-g-wodehouse_mr-mulliner-stories#1]
## General
- typogrify makes some valid changes!!

## content.opf
- typo: hiliarous
- long desc: Maybe a bit more about publication history? He wrote Mulliner stories from 1927-1970 publishing them first in serial then collections. A lot of the stories were rewrites of other stories etc. And isn't Mulliner an angler? These are literally "fish stories". 
- not sure the "sir" belongs in full name. It's not in any other entries I could find
- for future reference the `<meta property="se:role"` is deprecated. it is now `<meta property="role"` but leave it for Alex.

## came-the-dawn.xhtml
modernize spelling: supertaxes
- `<blockquote epub:type="z3998:verse">` line 98 This isn't verse? I can see how it might be styled that way but semantically its incorrect.

## Mulliners-buck-u-uppo.xhtml
- "Mem: Must guard agst" probably should have `<abbr>`

**Comment by jmcphers** [comment]
Thanks, these should all be addressed now!
